name: Jest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Deps
        run: yarn install

      - name: Create .env with Github Secrets and run script
        run: |
          touch .env
          echo ATLAS_URI=$ATLAS_URI >> .env
          cat .env
          yarn run test
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
